<!DOCTYPE HTML>
<html lang="<?php echo $this->Localization; ?>">
  <head>
	<meta charset="utf-8" />
	<title><?php echo $this->Title ?></title>
	<link rel="shortcut icon" href="static/theme/favicon.ico" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=3.0, user-scalable=yes" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta name="autosize" content="off" />
  </head>
  <body>
	<?php echo $this->GetContent(); ?>
  </body>
</html>
