<link href="static/js/libs/ext-6.0.0/theme-gray/resources/theme-gray-all-debug.css" rel="stylesheet" type="text/css" />
<link href="static/css/admin/base.css" rel="stylesheet" type="text/css" />
<link href="static/css/admin/font-awesome-face.css" rel="stylesheet" type="text/css" />
<link href="static/css/admin/files-tree.css" rel="stylesheet" type="text/css" />
<link href="static/css/admin/files-detail.css" rel="stylesheet" type="text/css" />
<link href="static/css/admin/files-types.css" rel="stylesheet" type="text/css" />
<link href="static/css/admin/ext-modifications.css" rel="stylesheet" type="text/css" />
		
<script type="text/javascript" src="static/js/libs/ext-6.0.0/ext-all-debug.js"></script>
<script type="text/javascript" src="static/js/libs/helpers/base64js.min.js"></script>
<script type="text/javascript" src="static/js/libs/helpers/admin.js"></script>
<script type="text/javascript" src="static/js/libs/class.min.js"></script>
<script type="text/javascript" src="static/js/libs/module.js"></script>
<script type="text/javascript" src="static/js/libs/sha1.min.js"></script>

<script type="text/javascript">
	var Settings = <?php echo json_encode($this->Settings); ?>;
	var Translations = <?php echo json_encode($this->Translations); ?>;
</script>

<script type="text/javascript" src="static/js/admin/app.js"></script>
